#let coverLett(papers) = [
I am a quantum condensed matter theorist, currently completing my Ph.D. in Physics at the Indian Institute of Science Education and Research (IISER) Kolkata under the supervision of *Prof. Siddhartha Lal*. My doctoral research focuses on *strongly correlated quantum matter*, in particular understanding Mott metal–insulator transitions and the emergence of non-Fermi liquid phases through the lens of *Kondo breakdown*. I anticipate that I will be able to join for a postdoctoral position by *March 2026*. I have been closely following your work on various interacting systems. In particular, I have been following your recent works on instabilities in altermagnetic materials and effect of interactions in bilayer graphene.

My own doctoral research work focuses on broadly similar questions but uses other methods. The main thrust of my work has been towards capturing various features (non-Fermi liquids and pseudogapping) of Mott transitions through *Kondo breakdown*; this has offered valuable insight into topological and momentum-selective transitions as well as patterns of entanglement near *quantum criticality*. More details can be found in my research statement.

I would like to describe one particular work (#link("https://arxiv.org/abs/2507.17201")[arXiv:2507.17201]) in more detail. Titled _Mott Criticality as the Confinement Transition of a Pseudogap-Mott Metal_, it introduces a *new impurity-model based approach* that maps the dynamics of a lattice-embedded impurity model to that of a full lattice model. Applying the approach to an extended Hubbard model reveals a *pseudogapped phase of matter with long-ranged entanglement and critical doublon-holon excitations*. This phase acts as the parent metal for the Mott insulator, and offers a *new route to Mott criticality* beyond the paradigm of local quantum criticality. 

Given the opportunity, I envisage several avenues for our collaboration that leverage my experience in correlated electronic models and entanglement calculations. These include (i) extending your work "Van-Hove singularities and competing instabilities in an altermagnetic metal" by studying changes in entanglement patterns, and (ii) an alternative angle of attacking the problem of MATBG: electronic interactions in the form of the exactly solvable Hatsugai-Kohmoto model. 

These lines of research, as well my own PhD work, are described in more detail in my research statement which I have attached with this email (in addition to my curriculum vitae and list of publications). I believe that my ability to quickly learn and adapt new analytical and numerical methods make me particularly suitable for this position. I would be happy to provide any additional information that you may require. A list of referees who have agreed to provide recommendation letters is included in my CV. Thank you for your time and consideration. I look forward to the possibility of contributing to your research community.
]
