#let coverLett(papers) = [
I am a quantum condensed matter theorist, currently completing my Ph.D. in Physics at the Indian Institute of Science Education and Research (IISER) Kolkata under the supervision of *Prof. Siddhartha Lal*. My doctoral research focuses on *strongly correlated quantum matter*, in particular understanding Mott metal–insulator transitions and the emergence of non-Fermi liquid phases through the lens of *Kondo breakdown*. I anticipate that I will be able to join for a postdoctoral position by *April 2026*. 

Given the appreciable overlap with my PhD work, I have followed your research with particular emphasis. Among the more recent ones, I particularly enjoyed yours work on (i) Fermi surface reconstruction in an *$N-$layer Hubbard model*, and (ii) transport properties in the presence of *Hatsugai-Kohmoto*-type interaction. In the past, I have also followed your series of works on *Luttinger's theorem* and Luttinger surfaces. These are especially significant to me because of the appearance of similar themes and models in my work (described in more detail in my research statement). I would welcome the opportunity to collaborate with you on any of these topics.

The majority of my doctoral research work is on capturing various features (non-Fermi liquids and pseudogapping) of Mott transitions in low dimensions, through *Kondo breakdown*. I have also worked on entanglement renormalization in free fermion systems and collaborated with *experimentalists* on lattice spin–phonon interactions in CrSiTe₃. These projects, described in detail in my research statement, reflect my (i) theoretical breadth, (ii) willingness to work on a variety of problems, and (iii) collaborative approach.

My *primary research interest* lies in understanding Mott transitions and correlation-driven metal–insulator transitions in *low-dimensional quantum materials*, particularly through the lens of Kondo breakdown. Specific aspects of my interest include emergent non-Fermi liquid phases, orbital/band-selective transitions, topology changes and changes in entanglement patterns, among others. Other topics that I am interested in and look forward to working on in the future include high-$T_c$ superconductivity and various topological phases.

I am working on several other projects which I plan to complete before joining for a postdoc. These include (i) studying quantum criticality in a model of *heavy-fermions*, from the perspective of Kondo breakdown, and (ii) looking for punctured-Chern invariant in *integer quantum hall* transitions.

Given the opportunity, I envisage several collaborative projects that combine our expertise. These include (i) studying effect of electronic correlations in magic-angle twisted bilayer graphene through an exactly solvable model, (ii) exploring violation of Luttinger's theorem in heavy-fermion systems, and (iii) fate of topological phases in the presence of interactions. These are explained in more detail in my research statement.

I believe that my ability to quickly *learn and adapt new methods*, both analytical and numerical, make me particularly suitable for this position. Enclosed are my curriculum vitae, research statement, and supporting materials. I would be glad to provide further information upon request. Thank you for your time and consideration. I look forward to the possibility of contributing to your research community.
]
