#let coverLett(papers) = [
I am currently completing my Ph.D. in Physics at the Indian Institute of Science Education and Research (IISER) Kolkata under the supervision of *Prof. Siddhartha Lal*. My doctoral research focuses on *strongly correlated quantum matter*, in particular understanding Mott metal–insulator transitions and the emergence of non-Fermi liquid phases through the lens of *Kondo breakdown*. I anticipate that I will be able to join for a postdoctoral position by *February 2026*.

My doctoral research work spans a number of themes, with a primary focus on capturing various features (non-Fermi liquids and pseudogapping) of Mott transitions through *Kondo breakdown*. I have also worked on entanglement renormalization in free fermion systems and collaborated with *experimentalists* on lattice spin–phonon interactions in CrSiTe₃. These projects, described in detail in my research statement, reflect my (i) theoretical breadth, (ii) willingness to work on a variety of problems, and (iii) collaborative approach.

I am working on several other projects which I plan to complete before joining for a postdoc. These include (i) studying quantum criticality in a model of *heavy-fermions*, from the perspective of Kondo breakdown, and (ii) looking for punctured-Chern invariant in *integer quantum hall* transitions.

Among the faculty members at UIUC, I have been closely following the work of *Prof. Philip W Phillips* on Mottness, generalised anomalies and unparticles in strongly-correlated quantum matter, in particular the body of research that focuses on the Hatsugai-Kohmoto model. My own research is along similar lines, exploring similar phenomena from the perspective of quantum impurity models. I believe this overlap in our research directions can lead to meaningful collaboration. Given my experience with renormalisation group methods, numerical computation of correlation functions and exploration of entanglement measures in various interacting models, I envision several interesting lines of research, such as (i) using the HK model to study the physics of magic-angle TBG, (ii) investigating Luttinger theorem violation in heavy-fermion materials, and (iii) looking for manybody scars in HK-type models. I explain two of these ideas in more detail: 

- *Studying effect of electronic correlations in MATBG through an exactly solvable model*. As mentioned in a previous point, the Hatsugai-Kohmoto model is an exactly solvable model of correlated electrons, displaying non-Fermi liquid and Mott insulating phases. This therefore provides an interesting route to studying the emergence of novel phases in a correlated MATBG system. Instabilities towards non-BCS superconductivity can also be explored and compared against experiments.

- *Exploring violation of Luttinger's theorem in heavy-fermion systems*. A growing body of recent literature suggests that violation of Luttinger's theorem (in non-Fermi liquids and Mott insulators) are a result of changes in the anomaly structure of the Fermi surface. One can investigate these claims particularly in the context of heavy-fermion systems to see if we can write down topological order parameters (derived from singularities in the Luttinger-Ward functional) that track phase transitions in such systems. One can also consider the question of correlating such anomalies to entanglement patterns.

I believe that my ability to quickly learn and adapt new analytical and numerical methods make me particularly suitable for this position. Looking ahead, I aim to build on this by investigating *universal aspects* of quantum criticality, particularly developing a unifying framework for fermionic criticality. I am particularly interested in exploring the role of topology and entanglement in such phase transitions. I believe that my ability to quickly *learn and adapt new methods*, both analytical and numerical, make me particularly suitable for this position.

Enclosed are my curriculum vitae, research statement, and supporting materials. I would be glad to provide further information upon request. Thank you for your time and consideration. I look forward to the possibility of contributing to your research community.
]
